"use client";

import {
  Sun,
  Moon,
  Send,
  Plus,
  Trash2,
  Edit3,
  Copy,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  X,
  Search,
  Globe,
  Paperclip,
  FileText,
  Image as ImageIcon,
  Code,
  ExternalLink,
  MoreHorizontal,
  MessageSquare,
  Sparkles,
  Loader2,
  Check,
  PanelLeftClose,
  PanelLeftOpen,
  Bot,
  User,
  AlertCircle,
  Info,
  BookOpen,
  RotateCcw,
  GitBranch,
  Play,
  Pause,
  Maximize2,
  Minimize2,
  Download,
  Share2,
  Settings,
  HelpCircle,
  Zap,
  Menu,
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
} from "lucide-react";

export const Icons = {
  sun: Sun,
  moon: Moon,
  send: Send,
  plus: Plus,
  trash: Trash2,
  edit: Edit3,
  copy: Copy,
  refresh: RefreshCw,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  x: X,
  search: Search,
  globe: Globe,
  paperclip: Paperclip,
  fileText: FileText,
  image: ImageIcon,
  code: Code,
  externalLink: ExternalLink,
  moreHorizontal: MoreHorizontal,
  messageSquare: MessageSquare,
  sparkles: Sparkles,
  loader: Loader2,
  check: Check,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  bot: Bot,
  user: User,
  alertCircle: AlertCircle,
  info: Info,
  bookOpen: BookOpen,
  rotateCcw: RotateCcw,
  gitBranch: GitBranch,
  play: Play,
  pause: Pause,
  maximize: Maximize2,
  minimize: Minimize2,
  download: Download,
  share: Share2,
  settings: Settings,
  help: HelpCircle,
  zap: Zap,
  menu: Menu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  eye: Eye,
  eyeOff: EyeOff,
};

export type IconName = keyof typeof Icons;
